### ISSUE TITLE
Support Newer Clang

### ISSUE THREAD

**Issue by akleeman** [swift-nav/albatross#100]
Current attempts to get clang format tests to work on travis only work with clang 3.8.

**Comment by martin-swift** [comment]
Right... because Travis only supports ancient Ubuntu 14.04 or something?  Can we migrate albatross over to Jenkins?  @schniedergers  clang-3.8 definitely has formatting differences from >= 4.0

**Comment by schniedergers** [comment]
Happy to migrate it over incl newer clang @martin-swift, maybe make me a ticket in EO.
