### ISSUE TITLE
nlopt.hpp 

### ISSUE THREAD

**Issue by gmnamra** [swift-nav/albatross#132]
macos / Xcode Version 10.2.1 (10E1001)

In file included from 
...../albatross/tests/test_model_metrics.cc:15:
...../albatross/include/albatross/Tune:16:10: fatal error: 'nlopt.hpp' file not found
#include <nlopt.hpp>

**Comment by silverjam** [comment]
The `nlopt` needs to be installed system wide currently.  Try running `brew install nlopt` if you use Homebrew -- Albatross doesn't currently submodule/vendor in nlopt.
